# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, setup-actions ]
  pull_request:
    branches: [ master, setup-actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds the voices
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # needs: prereq
    env:
      ESTDIR: ~/speech_tools
      FESTVOXDIR: ~/festvox
      LC_ALL: C.UTF-8
      G2P_MODEL_DIR: /home/runner/g2p-lstm
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get g2p model
        run: |
          cd
          git clone https://github.com/grammatek/g2p-lstm.git
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up voice dirs
        run: |
          cd $GITHUB_WORKSPACE
          cp -r $GITHUB_WORKSPACE/voice $GITHUB_WORKSPACE/voice_alfur
          ls $GITHUB_WORKSPACE/voice_alfur
          cp -r $GITHUB_WORKSPACE/voice $GITHUB_WORKSPACE/voice_dilja
          ls $GITHUB_WORKSPACE/voice_dilja
      - name: 'Build container'
        run: |
          cd $GITHUB_WORKSPACE
          docker build . --tag lvl-us-is-train -f train.Dockerfile
      - name: 'Build voices'
        run: |
          cd $GITHUB_WORKSPACE
          docker run -v speech-corpora:/usr/local/src/ext/data -v ${G2P_MODEL_DIR}:/app/fairseq_g2p -v ${PWD}/voice_alfur/:/usr/local/src/voice_alfur -v ${PWD}/voice_dilja/:/usr/local/src/voice_dilja lvl-us-is-train:latest
        # run: |
        #   source $HOME/miniconda/bin/activate
        #   conda activate fairseq-lstm
        #   cd $GITHUB_WORKSPACE
        #   cd voice_alfur
        #   ./run.sh ../ext/data_alfur standard 2000
        #   cp wav ~/wav_alfur
        #   cp ../index.tsv ~/index_alfur.tsv
        #   cd ../voice_dilja
        #   ./run.sh ../ext/data_dilja standard 2000
        #   cp wav ~/wav_dilja
        #   cp ../index.tsv ~/index_dilja.tsv

